LANGUAGE_MAP = {
  "en": "English",
  "ja": "Japanese",
  "ar": "Arabic",
  "so": "Somali",
  "pa": "Punjabi",
  "de": "German",
  "ha": "Hausa",
  "ur": "Urdu",
  "cy": "Welsh",
  "el": "Greek",
  "ca": "Catalan",

  "fr": "French",
  "es": "Spanish",
  "zh": "Chinese",
  "hi": "Hindi",
  "pt": "Portuguese",
  "ru": "Russian",
  "it": "Italian",
  "ko": "Korean",
  "vi": "Vietnamese",
  "tr": "Turkish",
  "nl": "Dutch",
  "sv": "Swedish",
  "pl": "Polish",
  "ro": "Romanian",
  "fa": "Persian",
  "he": "Hebrew",
  "th": "Thai",
  "bn": "Bengali",
  "ms": "Malay",
  "tl": "Tagalog",
  "id": "Indonesian"
}