# Docs for the Azure Web Apps Deploy action: https://github.com/azure/functions-action
# More GitHub Actions for Azure: https://github.com/Azure/actions
# More info on Python, GitHub Actions, and Azure Functions: https://aka.ms/python-webapps-actions

name: Build and deploy Python project to Azure Function App - cdc-tweets-ingestion

on:
  push:
    branches:
      - main
    paths:
      - 'tweets-ingestion-app/**'
      - '.github/workflows/main_cdc-tweets-ingestion.yml'
  workflow_dispatch:

env:
  AZURE_FUNCTIONAPP_PACKAGE_PATH: 'tweets-ingestion-app' # set this to the path to your web app project, defaults to the repository root
  PYTHON_VERSION: '3.12' # set this to the python version to use (supports 3.6, 3.7, 3.8)
  RESOURCE_GROUP: 'cdc-tweets-analysis'

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ${{ env.AZURE_FUNCTIONAPP_PACKAGE_PATH }}
    permissions:
      contents: read #This is required for actions/checkout

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Python version
        uses: actions/setup-python@v5
        with:
          python-version: ${{ env.PYTHON_VERSION }}

      - name: Create and start virtual environment
        run: |
          python -m venv venv
          source venv/bin/activate

      - name: Install dependencies
        run: pip install -r requirements.txt

      # Optional: Add step to run tests here

      - name: Zip artifact for deployment
        run: zip -r release.zip . -x "*.git*" ".venv/*" "__pycache__/*"

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: python-app
          path: ${{ env.AZURE_FUNCTIONAPP_PACKAGE_PATH }}/release.zip

  deploy:
    runs-on: ubuntu-latest
    needs: build
    
    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: python-app

      - name: Unzip artifact for deployment
        run: unzip release.zip  

      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_SP_CREDENTIALS }}   

      - name: Deploy to Azure Function App using CLI
        run: |
          az functionapp deployment source config-zip \
            --resource-group ${{ env.RESOURCE_GROUP }} \
            --name ${{ env.AZURE_FUNCTIONAPP_NAME }} \
            --src release.zip
        
      # - name: 'Deploy to Azure Functions'
      #   uses: Azure/functions-action@v1
      #   id: deploy-to-function
      #   with:
      #     app-name: 'cdc-tweets-ingestion'
      #     slot-name: 'Production'
      #     package: '.'
      #     publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_2210C2C6C6FD459EA7A2D1A5B461FB40 }}
      #     sku: 'flexconsumption'
        